version: '3.7'
services:
  website:
    build: .
    ports:
      - 5000:5000
    environment:
      MONGO_URL: mongodb://mymongo:27017/dev-ops-workshop
      PORT: 5000
      ADDRESS: localhost
  mymongo:
    image: mongo:4.2.3-bionic
    #ports:
    #  - 27017:27017
